### ISSUE TITLE
CI не работает

### ISSUE THREAD

**Issue by Xini1** [VladimirBabin/Hotel-Management-Application#40]
https://github.com/VladimirBabin/Hotel-Management-Application/blob/main/.github/workflows/github-actions-demo.yml - какой-то непонятный workflow

Также в логе последнего коммита написано что ни один тест не был запущен
![image](https://user-images.githubusercontent.com/59248517/230902361-c606e727-2dfd-442a-9fff-595f3a4cc401.png)
т.е. CI не настроен

**Comment by VladimirBabin** [comment]
Deleted demo workflow

**Comment by VladimirBabin** [comment]
Исправлено
